### ISSUE TITLE
非常好的app，如何实现开机就启动而不是每次都按下按钮

### ISSUE THREAD

**Issue by 11fen** [kaputnikGo/PilferShushJammer#10]
Turn off every night, turn on the app and press the passive button every time you turn it on. Can you turn on automatically without pressing the passive button?
每天晚上关机，开机后每次都要开启这个app并且按下被动按钮。能不能实现开机就自动运行，而不需要按下那个被动按钮

**Comment by kaputnikGo** [comment]
Google translate: "Very good app, how to achieve booting instead of pressing the button every time".
 I do not know what you mean when you say booting. What do you mean?

**Comment by 11fen** [comment]
I want to automatically lock the microphone when the phone is turned on, without pressing the "passive" button.

**Comment by kaputnikGo** [comment]
The example of the Lenscap app uses a special admin function API to turn off the camera. This function "com.android.settings.DeviceAdminSettings" can be set and it will stay set. More informatio here: https://developer.android.com/guide/topics/admin/device-admin  . There is no similar admin function for the microphone.
To create something like it would mean making the PilferShush app listen for and automatically load at boot and reset the jammer. That isnt something i want to do at this stage.

**Comment by 11fen** [comment]
Thank you, it feels that this is not very convenient. Press the “passive” button again after each restart of the phone. This application is a daily necessity.

**Comment by kaputnikGo** [comment]
I understand, however I will put boot listen on the list of possible features to add but cant promise anything at this stage.

**Comment by 1anomaly1** [comment]
I'LL ECHO THE NEED FOR "ALWAYS ON OPTION",  EVEN AFTER RESTART. HOWEVER, THE LATEST UPDATE PUT THE PASSIVE BUTTON INCONVENIENTLY TO THE TOP LEFT OF SCREEN, WHICH IS ENOUGH FOR ME TO DOWNGRADE. IT WASN'T ENOUGH TO ORIGINALLY HAVE THE MOST COMMONLY USED BUTTON ON THE LEFT SIDE, BUT NOW IT'S AT THE TOP LEFT!!!! DID YOU GET JIZZ STUCK IN THE KEYBOARD, OR ARE YOU LISTENING TO FAGGOTS TELL U HOW TO SCREW YOURSELF OVER? GREAT APP OTHERWISE, AND IS VERY IMPORTANT, BUT LETS NOT LET THE IDIOTS HAVE THEIR SAY IN JACKING THIS APP UP. WHOEVER THOUGHT TO PUT PASSIVE BUTTON AT TOP LEFT, INSTEAD OF BOTTOM RIGHT, IS A WORTHLESS FAGGOT TRYING TO PASSIVELY SABOTAGE A GREAT APP, OR YOU MUST HAVE JUST GOT DONE WITH A "JACKATHON", AND DECIDED TO APPEASE LEFT HANDED WEIRDO'S. WEIRDO'S THAT LOVE TO REACH FURTHER UP THE SCREEN, RATHER THAN THE MOST NATURAL, SHORTEST SPOT ON THE SCREEN FOR RIGHT HANDED SUPREMACY.
