### ISSUE TITLE
Audio Of Streamed Music Increases When Passive Jammer Active

### ISSUE THREAD

**Issue by puppykickr** [kaputnikGo/PilferShushJammer#11]
I recently noticed that when I am streaming music, namely from Radio Droid, that the volume of the media increases markedly when the passive jammer is activated.

If the music is streaming before the jammer is employed, Radio Droid stops.

To replicate issue:

Open RadioDroid, and select music source (I recommend La Grosse Radio Métal :) )

Open PilferShush, and activate passive jammer

(RadioDroid stops)

Open PilferShush, and activate passive jammer

Open RadioDroid, and select music source (I recommend La Grosse Radio Métal :) )

Note increase in volume from before

I am using a ZTE 558VL running 7.1.1 with a set of powered external speakers.

Also noted that sound enhancement software doesn't function when the passive jammer is active.

As any increase in volume output is usually desireable, I decided to try to utilize this as a feature.

I attempted to use Noozxoide EIZO-rewire PRO at this time, but it will not function if the passive jammer is running.

I am thinking that these issues stem from the way sound and music enhancement apps can interfere with each other, and so generally only one will run at a time.

This did not occur in previous versions of the app.

**Comment by kaputnikGo** [comment]
hmm,  i think that this may have something to do with the EQ checking routine that is run when testing for device abilities. 

Thanks for the bug report :) I will look into this.

**Comment by kaputnikGo** [comment]
ok, have update the app and released to google play and here (which fdroid should pick up on in some days...).
the EQ checking function still checks for the existence of an EQ and any band divisions but doesnt really do anything at all. i left it in for when (if ever) the active jammer gets updated to a native version. it would seem that changing the eq is NOT application specific but instead operates across the whole device - which probably makes sense. This would explain some of the volume differences as some freq bands were boosted, others squashed. 

But the other thing that may be occurring is the output audio check routine instantiates an audio track object to test device capabilities and sets a volume level as part of this. Then it destroys the audioTrack object but it would appear the volume level stays set. So now the output audio check is only run if and when the Active Jammer is engaged. App init and passive jammer run will check the record audio capabilities only. The bumping of any audio apps that are already running is more than likely to be caused by the Jammer's audio focus request, so this is now only done when active jammer is started.

hopefully this fixes those problems,
and thanks again for the bug report!!

**Comment by puppykickr** [comment]
Cool.
Always glad to be of any help for such a useful app.

Grant Ryan Swan
(puppykicker)
