### ISSUE TITLE
Option to start application on boot

### ISSUE THREAD

**Issue by dmlemos** [kaputnikGo/PilferShushJammer#21]
Hi. I love the concept of this app, would it be possible to have an option to start it on boot?

**Comment by kaputnikGo** [comment]
already requested https://github.com/kaputnikGo/PilferShushJammer/issues/19

**Comment by dmlemos** [comment]
I don't think #19 has closed this issue. Would be great to have this feature, otherwise it kind of defeats the whole purpose.

**Comment by kaputnikGo** [comment]
Yeah good point, #19 is a mixed issue, so will re-open this one as reference for the boot listener.

**Comment by kaputnikGo** [comment]
next release 4.5.0 will have boot receiver and auto restart at boot

**Comment by kaputnikGo** [comment]
boot listener/receiver may not be allowed to auto start the mic blocker service due to API rules but am still playing around with it. Also Android 11 (API 30) has more changes to microphone use that may impact a fair bit of this app's functions. This also being looked at now and i suspect these two things will be related.

**Comment by kaputnikGo** [comment]
Bug fix release 4.4.2 coming first. 4.5 will have to wait till i figure out what is going on with upcoming Android 11
