### ISSUE TITLE
Active protection, working?

### ISSUE THREAD

**Issue by Cyber-Talleyrand** [kaputnikGo/PilferShushJammer#35]
It looked that it is a very good project but has things to improve, it does not block properly other apps, the protection (actually) is poor, but is the best I have tried. There's only one thing that does not seem to work, the active protection, I have tried to record audio with my phone and other dispositives and all record perfectly even speaking lowly.

**Comment by c5c86a** [comment]
Isn't the active protection supposed to work on frequencies above the human ear? I hear it :)

**Comment by kaputnikGo** [comment]
The default audible tones is a Test mode so that you can be sure that the device is working properly. Going to the settings section allows you to switch to NUHF which is the jamming mode and consists of mainly inaudible audio but due to the software and device may have audible artifacts present that you can hear. Other settings change how that audio is created.
